//----------------------------------------------------------------------------------------------------------------------------
// Autogenerated file -- DO NOT EDIT
//
// This file was autogenerated by PeakRDL-svh
// Date (mm-dd-yyyy) : 07-08-2020  
// Time (hh:mm:ss)   : 17:00:19
//
// This package file includes the required define files
//----------------------------------------------------------------------------------------------------------------------------

`ifndef _EXAMPLE_REGISTER_DEFINES_PKG_INCLUDED_
`define _EXAMPLE_REGISTER_DEFINES_PKG_INCLUDED_

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Package: example_register_defines_pkg
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

package example_register_defines_pkg;
  `include "tru_cfg_defines.svh"
  `include "atxmega_spi_defines.svh"
endpackage: example_register_defines_pkg

`endif

